name: Contributor Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub Username of Contributor'
        required: true
        type: string

jobs:
  contributor-setup:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Get GitHub User Info
    - name: Fetch User Info from GitHub API
      id: fetch_user_info
      run: |
        # Fetch user info from GitHub API using the provided username
        response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/users/${{ github.event.inputs.username }}")

        # Extract the name and email from the response
        USERNAME=$(echo "$response" | jq -r '.login')
        NAME=$(echo "$response" | jq -r '.name')
        EMAIL=$(echo "$response" | jq -r '.email')

        # Set the user details as outputs
        echo "USER_NAME=$NAME" >> $GITHUB_ENV
        echo "USER_EMAIL=$EMAIL" >> $GITHUB_ENV
        echo "USER_USERNAME=$USERNAME" >> $GITHUB_ENV

    # Step 3: Check GitHub API Rate Limit
    - name: Check GitHub API Rate Limit
      id: rate_limit
      run: |
        rate_limit=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit | jq '.resources.core.remaining')
        if [ "$rate_limit" -lt 10 ]; then
          echo "Rate limit is low. Exiting."
          exit 1
        fi

    # Step 4: Set up Git Config with Fetched User Info
    - name: Set up Git Config
      run: |
        git config --local user.name "${{ env.USER_NAME }}"
        git config --local user.email "${{ env.USER_EMAIL }}"

    # Step 5: Create folders and content for the contributor
    - name: Create Contributor Folder and Content
      run: |
        # Create folder structure for the contributor
        mkdir -p Contributors/${{ github.event.inputs.username }}
        
        # Create static content for the contributor
        echo "# About ${{ github.event.inputs.username }}" > Contributors/${{ github.event.inputs.username }}/ABOUT.md
        echo "This folder contains content and contributions from ${{ github.event.inputs.username }}" >> Contributors/${{ github.event.inputs.username }}/ABOUT.md

        # Create self.md with some details
        echo "# ${{ github.event.inputs.username }}'s Personal Information" > Contributors/${{ github.event.inputs.username }}/self.md
        echo "GitHub Username: ${{ env.USER_USERNAME }}" >> Contributors/${{ github.event.inputs.username }}/self.md
        echo "Email: ${{ env.USER_EMAIL }}" >> Contributors/${{ github.event.inputs.username }}/self.md
        echo "Twitter: @${{ github.event.inputs.username }}" >> Contributors/${{ github.event.inputs.username }}/self.md
        echo "Patreon: (provide patreon link if available)" >> Contributors/${{ github.event.inputs.username }}/self.md

    # Step 6: Create a new branch for the contributor and commit changes
    - name: Commit and Push Changes
      run: |
        # Create a new branch for the contributor
        git checkout -b contributor/${{ github.event.inputs.username }}
        
        # Stage and commit the changes
        git add .
        git commit -m "Add ${{ github.event.inputs.username }}'s folder and static content"
        
        # Push the changes to the repository
        git push origin contributor/${{ github.event.inputs.username }}
