name: Generate Static Content for Kukks Bitcoin Payment Processor

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  # Single job for creating static content and pushing changes
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create directory and files for Bitcoin Payment Processor
        run: |
          # Create directory for Bitcoin Payment Processor
          mkdir -p kukks-payment-processor

          # Create user-details.json
          echo '{
            "username": "Kukks",
            "followers": 428,
            "following": 53,
            "email": "evilkukka@gmail.com",
            "bio": "Accept Bitcoin payments. Free, open-source & self-hosted, Bitcoin payment processor.",
            "github_url": "https://github.com/btcpayserver/btcpayserver"
          }' > kukks-payment-processor/user-details.json

          # Create index.html
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta name="description" content="Bitcoin payment processor. Open-source & self-hosted.">
              <title>Kukks Bitcoin Payment Processor</title>
          </head>
          <body>
              <header>
                  <h1>Welcome to Kukks\' Bitcoin Payment Processor</h1>
                  <p>Accept Bitcoin payments using this open-source and self-hosted solution.</p>
              </header>
              <footer>
                  <p>For more information, visit <a href="https://github.com/btcpayserver/btcpayserver" target="_blank">BTCPayServer GitHub</a>.</p>
              </footer>
          </body>
          </html>' > kukks-payment-processor/index.html

          # Create README.md
          echo '# Kukks Bitcoin Payment Processor

          A free, open-source, self-hosted Bitcoin payment processor.

          ## Features
          - Open-source
          - Self-hosted
          - Bitcoin payment processing

          ## How to Use
          1. Clone the repository.
          2. Deploy on your server.
          3. Set up Bitcoin wallet integration.

          ## GitHub
          [BTCPayServer on GitHub](https://github.com/btcpayserver/btcpayserver)

          ## Contact
          Email: [evilkukka@gmail.com](mailto:evilkukka@gmail.com)' > kukks-payment-processor/README.md

          # Commit and push the changes to GitHub
          git add .
          git commit -m "Add Bitcoin payment processor files for Kukks"
          git push origin main
